version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-2004:202104-01
    steps:
      - checkout
      - run: ls
      - run: pwd
      - run: docker build -t django-web:$CIRCLE_SHA1 .
      - run: docker tag django-web:$CIRCLE_SHA1 259677325264.dkr.ecr.us-east-1.amazonaws.com/django-web:$CIRCLE_SHA1
      - run: aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 259677325264.dkr.ecr.us-east-1.amazonaws.com
      - run: docker push 259677325264.dkr.ecr.ue-east-1.amazonaws.com/django-web:$CIRCLE_SHA1
