version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-2004:202104-01
    steps:
      - checkout
      - run: ls
      - run: pwd
      - run: docker build .
      - run: docker tag django-web:latest django-web:$CIRCLE_SHA1
